// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: cat.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CatServiceClient is the client API for CatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatServiceClient interface {
	AddCat(ctx context.Context, in *Cat, opts ...grpc.CallOption) (*Cat, error)
}

type catServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatServiceClient(cc grpc.ClientConnInterface) CatServiceClient {
	return &catServiceClient{cc}
}

func (c *catServiceClient) AddCat(ctx context.Context, in *Cat, opts ...grpc.CallOption) (*Cat, error) {
	out := new(Cat)
	err := c.cc.Invoke(ctx, "/pb.CatService/AddCat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatServiceServer is the server API for CatService service.
// All implementations must embed UnimplementedCatServiceServer
// for forward compatibility
type CatServiceServer interface {
	AddCat(context.Context, *Cat) (*Cat, error)
	mustEmbedUnimplementedCatServiceServer()
}

// UnimplementedCatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCatServiceServer struct {
}

func (UnimplementedCatServiceServer) AddCat(context.Context, *Cat) (*Cat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCat not implemented")
}
func (UnimplementedCatServiceServer) mustEmbedUnimplementedCatServiceServer() {}

// UnsafeCatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatServiceServer will
// result in compilation errors.
type UnsafeCatServiceServer interface {
	mustEmbedUnimplementedCatServiceServer()
}

func RegisterCatServiceServer(s grpc.ServiceRegistrar, srv CatServiceServer) {
	s.RegisterService(&CatService_ServiceDesc, srv)
}

func _CatService_AddCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).AddCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatService/AddCat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).AddCat(ctx, req.(*Cat))
	}
	return interceptor(ctx, in, info, handler)
}

// CatService_ServiceDesc is the grpc.ServiceDesc for CatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CatService",
	HandlerType: (*CatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCat",
			Handler:    _CatService_AddCat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cat.proto",
}
